// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetZORK.DataAccessLayer;

namespace ProjetZORK.DataAccessLayer.Migrations
{
    [DbContext(typeof(ZorkManagerDbContext))]
    [Migration("20210212103440_Bddv1")]
    partial class Bddv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonsterRate")
                        .HasColumnType("int");

                    b.Property<int>("PosX")
                        .HasColumnType("int");

                    b.Property<int>("PosY")
                        .HasColumnType("int");

                    b.Property<bool>("canMoveTo")
                        .HasColumnType("bit");

                    b.Property<int>("gameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackRate")
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int>("MissRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.ObjectPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ObjectTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ObjectPlayers");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackStrenghBoost")
                        .HasColumnType("int");

                    b.Property<int>("DefenseBoost")
                        .HasColumnType("int");

                    b.Property<int>("HPRestoreValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObjectTypes");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.Property<int?>("currentCellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("currentCellId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackRate")
                        .HasColumnType("int");

                    b.Property<int>("MissRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("playerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("playerId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.ObjectPlayer", b =>
                {
                    b.HasOne("ProjetZORK.DataAccessLayer.Models.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectTypeId");

                    b.HasOne("ProjetZORK.DataAccessLayer.Models.Player", "Player")
                        .WithMany("ObjectInventory")
                        .HasForeignKey("PlayerId");

                    b.Navigation("ObjectType");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.Player", b =>
                {
                    b.HasOne("ProjetZORK.DataAccessLayer.Models.Cell", "currentCell")
                        .WithMany()
                        .HasForeignKey("currentCellId");

                    b.Navigation("currentCell");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.Weapon", b =>
                {
                    b.HasOne("ProjetZORK.DataAccessLayer.Models.Player", "player")
                        .WithMany("WeaponsInventory")
                        .HasForeignKey("playerId");

                    b.Navigation("player");
                });

            modelBuilder.Entity("ProjetZORK.DataAccessLayer.Models.Player", b =>
                {
                    b.Navigation("ObjectInventory");

                    b.Navigation("WeaponsInventory");
                });
#pragma warning restore 612, 618
        }
    }
}
